name: Publish JupyterBook to GitHub Pages

on: 
  push: # trigger build only when push to master
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        pip install git+git://github.com/executablebookproject/cli.git#egg=master
        PATH="${PATH}:${HOME}/.local/bin"

    - name: Create book template and build page HTML 
      run: |
        jupyter-book build ./content

    - name: Push _build/html to gh-pages
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        
        cp -r ./content/_build/html /tmp
        rm -rf *
        mv /tmp/html/* .
        git checkout -b gh-pages
        git add --all --force
        git commit -a --allow-empty-message -m ''
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        git push --force origin gh-pages 

